config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root"restaurants#index"

  resources :restaurants, only:[:index, :show] do
    resources :comments, only:[:create, :destroy]

    # 瀏覽所有餐廳的最新動態
    collection do
      get :feeds
    end

    # 瀏覽個別餐廳的 Dashboard
    member do
      get :dashboard
      post :favorite
      post :unfavorite
      post :like
      post :unlike
    end
  end

  resources :categories, only: :show
  root"restaurants#index"

  resources :users, only:[:index, :show, :edit, :update]

  resources :followships, only:[:create, :destroy]

  namespace :admin do
    resources :restaurants
    resources :categories
    root"restaurants#index"
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  validates_presence_of :name
  validates_uniqueness_of :name

  # 如果分類下已有餐廳，就不允許刪除分類（刪除時拋出 Error）
  has_many :restaurants, dependent: :restrict_with_error
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :restaurant
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :restaurant
end

app/models/followship.rb
class Followship < ApplicationRecord
  # 「使用者追蹤使用者」的 self-referential relationships 設定
  # 由於 :following 指向 User Model, Rails 無法自動推論
  # 使用 :class_name 告知對應的 Model 名稱
  belongs_to :user
  belongs_to :following, class_name:"User"

  validates :following_id, uniqueness:{scope: :user_id}
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :restaurant
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  validates_presence_of :name
  mount_uploader :image, PhotoUploader

  belongs_to :category
  has_many :comments, dependent: :destroy

  has_many :users, through: :favorites

  has_many :favorites, dependent: :destroy
  has_many :favorited_users, through: :favorites, source: :user

  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user

  def is_favorited?(user)
    self.favorited_users.include?(user)
  end

  def is_liked?(user)
    self.liked_users.include?(user)
  end
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  mount_uploader :avatar, PhotoUploader

  # 「使用者評論很多餐廳」的多對多關聯
  # 如果 User 已經有了評論，就不允許刪除帳號（刪除時拋出 Error）
  has_many :comments, dependent: :restrict_with_error
  has_many :restaurants, through: :comments

   # 「使用者收藏很多餐廳」的多對多關聯
  has_many :favorites, dependent: :destroy
  has_many :favorited_restaurants, through: :favorites, source: :restaurant

  has_many :likes, dependent: :destroy
  has_many :liked_restaurants, through: :likes, source: :restaurant

  # 「使用者追蹤使用者」的 self-referential relationships 設定
  # 不需要另加 source，Rails 可從 Followship Model 設定來判斷 followings 指向 User Model
  has_many :followships, dependent: :destroy
  has_many :followings, through: :followships

  # 「使用者的追蹤者」的設定
  # 透過 class_name, foreign_key 的自訂，指向 Followship 表上的另一側
  has_many :inverse_followships, class_name: "Followship", foreign_key: "following_id"
  has_many :followers, through: :inverse_followships, source: :user

  def admin?
    self.role == "admin"
  end

  def following?(user)
    self.followings.include?(user)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def show
    @categories = Category.all
    @category = Category.find(params[:id])
    @restaurants = @category.restaurants.page(params[:page]).per(9)
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @comment = @restaurant.comments.build(comment_params)
    @comment.user = current_user
    @comment.save!
    redirect_to restaurant_path(@restaurant)
  end

  def destroy
    @restaurant = Restaurant.find(params[:restaurant_id])
    @comment = Comment.find(params[:id])

    if current_user.admin? || current_user == comment.user
      @comment.destroy
      redirect_to restaurant_path(@restaurant)
    end
  end



private

  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/controllers/followships_controller.rb
class FollowshipsController < ApplicationController

  def create
    @followship = current_user.followships.build(following_id: params[:following_id])
    if @followship.save
      flash[:notice] = "Successfully followed"
      redirect_back(fallback_location: root_path)
    else
      flash[:alert] = @followship.errors.full_messages.to_sentence
      redirect_back(fallback_location: root_path)
    end
  end


def destroy
  @followship = current_user.followships.where(following_id: params[:id]).first
  @followship.destroy
  flash[:alert] = "Followship destroyed"
  redirect_back(fallback_location: root_path)
end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  def index
    @restaurants = Restaurant.page(params[:page]).per(9)
    @categories = Category.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
    @comment = Comment.new
  end

  def feeds
    @recent_restaurants = Restaurant.order(created_at: :desc).limit(10)
    @recent_comments = Comment.order(created_at: :desc).limit(10)
  end

  def dashboard
    @restaurant = Restaurant.find(params[:id])
  end

  def favorite
    @restaurant = Restaurant.find(params[:id])
    @restaurant.favorites.create!(user: current_user)
    redirect_back(fallback_location: root_path)
  end

  def unfavorite
    @restaurant = Restaurant.find(params[:id])
    favorites = Favorite.where(restaurant: @restaurant, user: current_user)
    favorites.destroy_all
    redirect_back(fallback_location: root_path)
  end

  def like
    @restaurant = Restaurant.find(params[:id])
    @restaurant.likes.create!(user: current_user)
    redirect_back(fallback_location: root_path)
  end

  def unlike
    @restaurant = Restaurant.find(params[:id])
    likes = Like.where(restaurant: @restaurant, user: current_user)
    likes.destroy_all
    redirect_back(fallback_location: root_path)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only:[:show, :edit, :update]

  def show
    @commented_restaurants = @user.restaurants
  end

  def edit
    unless @user == current_user
    redirect_to user_path(@user)
    end
  end

  def update
    @user.update(user_params)
    redirect_to user_path(@user)
  end

  def index
    @users = User.all
  end


private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :intro, :avatar)
  end

end

app/helpers/admin/base_helper.rb
module Admin::BaseHelper
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/admin/restaurants_helper.rb
module Admin::RestaurantsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/followships_helper.rb
module FollowshipsHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
 <div class="container">
   <div class="row">
     <div class="col-md-6 col-md-offset-3">

     <h3>My Profile</h3>

     <%= form_for @user do |f| %>
       <div class ="form-group">
         <%=f.label :name, "Name" %>
         <%=f.text_field :name, class:"form-control" %>
       </div>
       <div class ="form-group">
         <%=f.label :intro, "Intro" %>
         <%=f.text_area :intro, class:"form-control" %>
       </div>
       <div class ="form-group">
        <%=f.submit "Update", class:"btn btn-primary" %>
        <%= link_to "Cancel", user_path(@user), class: "btn btn-default" %>
       </div>
       <div class ="form-group">
         <%=f.label :avatar, "Photo" %>
         <%=image_tag @user.avatar if @user.avatar? %>
         <%=f.file_field :avatar %>
       </div>

     <% end %>

     </div>
   </div>
 </div>

app/views/users/index.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<h1>美食達人</h1>

<div class="container">
  <div class="row">
    <ul class="nav nav-tabs">
      <li><%= link_to '首頁', root_path %></li>
      <li><%= link_to '最新動態', feeds_restaurants_path %></li>
      <li class="active"><%= link_to '美食達人', users_path %></li>
    </ul>
  </div>
</div>

<div class="container">
  <div class="row">
      <% @users.each do |user| %>
        <div class="col-xs-6 col-md-3 text-center user-item">
          <div class="caption">
            <a href="https://placeholder.com"><img src="http://via.placeholder.com/200x200"></a>
            <h4><strong><%= link_to user.name, user_path(user) %></strong></h4>
            <h5><%= render partial:"shared/follow", locals:{user: user} %></h5>
          </div>
        </div>
      <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class ="container">
  <div class ="row">
    <div class="col-md-10 col-md-offset-1">

<!-- page-header 裡面顯示個人檔案資料 -->
      <div class="page-header">
        <div class="col-md-3 col-sm-4">
          <div class ="text-center">
            <%=image_tag @user.avatar, class:"img-responsive img-rounded" %>
          </div>
        </div>

        <div class ="col-md-9 col-sm-8">
          <h1><%= @user.name %></h1>
          <p><strong><%= @user.email %></strong></p>
          <p><%= simple_format @user.intro %></p>
          <% if @user.email == current_user.email %>
            <%= link_to 'Edit', edit_user_path, class:"btn btn-primary" %>
          <% end %>
        </div>
        <div class="clearfix"></div>
      </div>

      <br>

      <div class="panel panel-info">
        <div class="panel-heading">
          <h4 class="panel-title>"<strong><%= @commented_restaurants.count %></strong> 已評論餐廳</h4>
        </div>
        <div class="panel-body">
          <% @commented_restaurants.each do |restaurant| %>
          <%= link_to restaurant_path(restaurant) do %>
          <div class="my-restaurant">
            <%= image_tag restaurant.image, class: "img-responsive img-rounded" %>
            <h5><%= restaurant.name %></h5>
          </div>
          <% end %>
          <% end %>
        </div>
      </div>

    </div>
  </div>
</div>